/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminManageRouteImport } from './routes/admin/manage'
import { Route as ApiAdminUsersRouteImport } from './routes/api/admin/users'
import { Route as ApiAdminManagementRouteImport } from './routes/api/admin/management'
import { Route as ApiTrackVisitRouteImport } from './routes/api/track-visit'
import { Route as ApiAccountDeleteRouteImport } from './routes/api/account/delete'
import { Route as ApiAccountRestoreRouteImport } from './routes/api/account/restore'
import { Route as ApiAccountStatusRouteImport } from './routes/api/account/status'
import { Route as ApiPaystackCancelRouteImport } from './routes/api/paystack/cancel'
import { Route as ApiPaystackInitializeRouteImport } from './routes/api/paystack/initialize'
import { Route as ApiPaystackStatusRouteImport } from './routes/api/paystack/status'
import { Route as ApiPaystackWebhookRouteImport } from './routes/api/paystack/webhook'
import { Route as ApiPublicPromoRedeemRouteImport } from './routes/api/public/promo-redeem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminManageRoute = AdminManageRouteImport.update({
  id: '/admin/manage',
  path: '/admin/manage',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminUsersRoute = ApiAdminUsersRouteImport.update({
  id: '/api/admin/users',
  path: '/api/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminManagementRoute = ApiAdminManagementRouteImport.update({
  id: '/api/admin/management',
  path: '/api/admin/management',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackVisitRoute = ApiTrackVisitRouteImport.update({
  id: '/api/track-visit',
  path: '/api/track-visit',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountDeleteRoute = ApiAccountDeleteRouteImport.update({
  id: '/api/account/delete',
  path: '/api/account/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountRestoreRoute = ApiAccountRestoreRouteImport.update({
  id: '/api/account/restore',
  path: '/api/account/restore',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountStatusRoute = ApiAccountStatusRouteImport.update({
  id: '/api/account/status',
  path: '/api/account/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackCancelRoute = ApiPaystackCancelRouteImport.update({
  id: '/api/paystack/cancel',
  path: '/api/paystack/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackInitializeRoute = ApiPaystackInitializeRouteImport.update({
  id: '/api/paystack/initialize',
  path: '/api/paystack/initialize',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackStatusRoute = ApiPaystackStatusRouteImport.update({
  id: '/api/paystack/status',
  path: '/api/paystack/status',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaystackWebhookRoute = ApiPaystackWebhookRouteImport.update({
  id: '/api/paystack/webhook',
  path: '/api/paystack/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPromoRedeemRoute = ApiPublicPromoRedeemRouteImport.update({
  id: '/api/public/promo-redeem',
  path: '/api/public/promo-redeem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage': typeof AdminManageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/management': typeof ApiAdminManagementRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/restore': typeof ApiAccountRestoreRoute
  '/api/account/status': typeof ApiAccountStatusRoute
  '/api/paystack/cancel': typeof ApiPaystackCancelRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage': typeof AdminManageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/management': typeof ApiAdminManagementRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/restore': typeof ApiAccountRestoreRoute
  '/api/account/status': typeof ApiAccountStatusRoute
  '/api/paystack/cancel': typeof ApiPaystackCancelRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/manage': typeof AdminManageRoute
  '/api/admin/users': typeof ApiAdminUsersRoute
  '/api/admin/management': typeof ApiAdminManagementRoute
  '/api/track-visit': typeof ApiTrackVisitRoute
  '/api/account/delete': typeof ApiAccountDeleteRoute
  '/api/account/restore': typeof ApiAccountRestoreRoute
  '/api/account/status': typeof ApiAccountStatusRoute
  '/api/paystack/cancel': typeof ApiPaystackCancelRoute
  '/api/paystack/initialize': typeof ApiPaystackInitializeRoute
  '/api/paystack/status': typeof ApiPaystackStatusRoute
  '/api/paystack/webhook': typeof ApiPaystackWebhookRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/upgrade'
    | '/admin/'
    | '/admin/login'
    | '/admin/manage'
    | '/api/admin/users'
    | '/api/admin/management'
    | '/api/track-visit'
    | '/api/account/delete'
    | '/api/account/restore'
    | '/api/account/status'
    | '/api/paystack/cancel'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/webhook'
    | '/api/public/promo-redeem'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/upgrade'
    | '/admin/'
    | '/admin/login'
    | '/admin/manage'
    | '/api/admin/users'
    | '/api/admin/management'
    | '/api/track-visit'
    | '/api/account/delete'
    | '/api/account/restore'
    | '/api/account/status'
    | '/api/paystack/cancel'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/webhook'
    | '/api/public/promo-redeem'
  id:
    | '__root__'
    | '/'
    | '/upgrade'
    | '/admin/'
    | '/admin/login'
    | '/admin/manage'
    | '/api/admin/users'
    | '/api/admin/management'
    | '/api/track-visit'
    | '/api/account/delete'
    | '/api/account/restore'
    | '/api/account/status'
    | '/api/paystack/cancel'
    | '/api/paystack/initialize'
    | '/api/paystack/status'
    | '/api/paystack/webhook'
    | '/api/public/promo-redeem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UpgradeRoute: typeof UpgradeRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminManageRoute: typeof AdminManageRoute
  ApiAdminUsersRoute: typeof ApiAdminUsersRoute
  ApiAdminManagementRoute: typeof ApiAdminManagementRoute
  ApiTrackVisitRoute: typeof ApiTrackVisitRoute
  ApiAccountDeleteRoute: typeof ApiAccountDeleteRoute
  ApiAccountRestoreRoute: typeof ApiAccountRestoreRoute
  ApiAccountStatusRoute: typeof ApiAccountStatusRoute
  ApiPaystackCancelRoute: typeof ApiPaystackCancelRoute
  ApiPaystackInitializeRoute: typeof ApiPaystackInitializeRoute
  ApiPaystackStatusRoute: typeof ApiPaystackStatusRoute
  ApiPaystackWebhookRoute: typeof ApiPaystackWebhookRoute
  ApiPublicPromoRedeemRoute: typeof ApiPublicPromoRedeemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/manage': {
      id: '/admin/manage'
      path: '/admin/manage'
      fullPath: '/admin/manage'
      preLoaderRoute: typeof AdminManageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/users': {
      id: '/api/admin/users'
      path: '/api/admin/users'
      fullPath: '/api/admin/users'
      preLoaderRoute: typeof ApiAdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/management': {
      id: '/api/admin/management'
      path: '/api/admin/management'
      fullPath: '/api/admin/management'
      preLoaderRoute: typeof ApiAdminManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track-visit': {
      id: '/api/track-visit'
      path: '/api/track-visit'
      fullPath: '/api/track-visit'
      preLoaderRoute: typeof ApiTrackVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/delete': {
      id: '/api/account/delete'
      path: '/api/account/delete'
      fullPath: '/api/account/delete'
      preLoaderRoute: typeof ApiAccountDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/restore': {
      id: '/api/account/restore'
      path: '/api/account/restore'
      fullPath: '/api/account/restore'
      preLoaderRoute: typeof ApiAccountRestoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/status': {
      id: '/api/account/status'
      path: '/api/account/status'
      fullPath: '/api/account/status'
      preLoaderRoute: typeof ApiAccountStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/cancel': {
      id: '/api/paystack/cancel'
      path: '/api/paystack/cancel'
      fullPath: '/api/paystack/cancel'
      preLoaderRoute: typeof ApiPaystackCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/initialize': {
      id: '/api/paystack/initialize'
      path: '/api/paystack/initialize'
      fullPath: '/api/paystack/initialize'
      preLoaderRoute: typeof ApiPaystackInitializeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/status': {
      id: '/api/paystack/status'
      path: '/api/paystack/status'
      fullPath: '/api/paystack/status'
      preLoaderRoute: typeof ApiPaystackStatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/paystack/webhook': {
      id: '/api/paystack/webhook'
      path: '/api/paystack/webhook'
      fullPath: '/api/paystack/webhook'
      preLoaderRoute: typeof ApiPaystackWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/promo-redeem': {
      id: '/api/public/promo-redeem'
      path: '/api/public/promo-redeem'
      fullPath: '/api/public/promo-redeem'
      preLoaderRoute: typeof ApiPublicPromoRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UpgradeRoute: UpgradeRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminManageRoute: AdminManageRoute,
  ApiAdminUsersRoute: ApiAdminUsersRoute,
  ApiAdminManagementRoute: ApiAdminManagementRoute,
  ApiTrackVisitRoute: ApiTrackVisitRoute,
  ApiAccountDeleteRoute: ApiAccountDeleteRoute,
  ApiAccountRestoreRoute: ApiAccountRestoreRoute,
  ApiAccountStatusRoute: ApiAccountStatusRoute,
  ApiPaystackCancelRoute: ApiPaystackCancelRoute,
  ApiPaystackInitializeRoute: ApiPaystackInitializeRoute,
  ApiPaystackStatusRoute: ApiPaystackStatusRoute,
  ApiPaystackWebhookRoute: ApiPaystackWebhookRoute,
  ApiPublicPromoRedeemRoute: ApiPublicPromoRedeemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
