/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UpgradeRouteImport } from './routes/upgrade'
import { Route as ApiPublicPromoRedeemRouteImport } from './routes/api/public/promo-redeem'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UpgradeRoute = UpgradeRouteImport.update({
  id: '/upgrade',
  path: '/upgrade',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPromoRedeemRoute = ApiPublicPromoRedeemRouteImport.update({
  id: '/api/public/promo-redeem',
  path: '/api/public/promo-redeem',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/upgrade': typeof UpgradeRoute
  '/api/public/promo-redeem': typeof ApiPublicPromoRedeemRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/upgrade' | '/api/public/promo-redeem'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/upgrade' | '/api/public/promo-redeem'
  id: '__root__' | '/' | '/upgrade' | '/api/public/promo-redeem'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UpgradeRoute: typeof UpgradeRoute
  ApiPublicPromoRedeemRoute: typeof ApiPublicPromoRedeemRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upgrade': {
      id: '/upgrade'
      path: '/upgrade'
      fullPath: '/upgrade'
      preLoaderRoute: typeof UpgradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/promo-redeem': {
      id: '/api/public/promo-redeem'
      path: '/api/public/promo-redeem'
      fullPath: '/api/public/promo-redeem'
      preLoaderRoute: typeof ApiPublicPromoRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UpgradeRoute: UpgradeRoute,
  ApiPublicPromoRedeemRoute: ApiPublicPromoRedeemRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
